server:
  port: 9081
spring:
  application:
    name: basic-service
  config:
    import:
      - classpath:application-filter.yml
      - classpath:application-db.yml
## jwt 配置
jwt:
  # 密钥字符串（256位）
  secret-key: XioEqEG2bHV/AkH6s9fVTFF2BIdvMoUL
  # token有效时间（单位：毫秒）
  expire-time: 3600000
  refresh-expire-time: 28800000
  # token前缀
  prefix: 'Bearer '
  # token头文件名
  header: Authorization
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: '基础档案模块'
      paths-to-match: '/basic/**'
      packages-to-scan: com.italycalibur.ciallo.wms.basic
  show-login-endpoint: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
    enable-version: true # 是否开启界面中对某接口的版本控制,如果开启，后端变化后Ui界面会存在小蓝点
    enable-filter-multipart-apis: true # RequestMapping接口,是否开启过滤
    enable-filter-multipart-api-method-type: GET # RequestMapping只展示哪种类型
    enable-footer-custom: true # 开启自定义页脚
    footer-custom-content: <strong>MIT License | Copyright  2025 - [italycalibur2019](https://github.com/italycalibur2019)</strong>
